### ISSUE TITLE
Le service pdf-text renvoit une réponse  vide

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/web-services#110]
Via lodex, le web service pdf-text appelé avec des urls fonctionnent sur plusieurs urls mais pour certaines Lodex affiche l'erreur :

![image](https://github.com/Inist-CNRS/web-services/assets/15609/254193b2-adcf-4c20-b02a-eeb9e9527161) 

En cherchant un peu, il se trouve que la réponse du web service est vide 
![image](https://github.com/Inist-CNRS/web-services/assets/15609/1a257b4b-3991-4bf6-a2bf-1e34a9b57288)

coté web service il y a aussi une erreur laconique... 

```
<Error: ./v1/pdf2txt.py exit with code 1>

```

De manière isolée le même appel via swagger sur la même url ne pose pas de problème...

**Comment by touv** [comment]
mea culpa j'ai trouvé une erreur plus précise coté serveur 
![image](https://github.com/Inist-CNRS/web-services/assets/15609/5e44f2f8-1868-40c8-a9aa-fae5324e7a3d)

**Comment by touv** [comment]
sauf que dans ce cas lodex affiche bien l'erreur (donc la réponse n'est pas vide)

![image](https://github.com/Inist-CNRS/web-services/assets/15609/d780c303-1514-4c2d-b072-2593067f334b)

Conclusion, il y a plusieurs cas...

**Comment by cuxac** [comment]
Tu peux me donner une url de pdf qui provoque ce comportement ?

**Comment by touv** [comment]
je crois que c'est pas toujours le même pdf, ou le même lot de fichiers

**Comment by cuxac** [comment]
aïe

**Comment by touv** [comment]
il ya plusieurs cas:

cette ligne https://github.com/Inist-CNRS/web-services/blob/main/services/pdf-text/v1/pdf2txt.py#L35

ou cette ligne https://github.com/Inist-CNRS/web-services/blob/main/services/pdf-text/v1/pdf2txt.py#L218

**Comment by touv** [comment]
sans être spécialiste python, je dirais que la première provoque l'arret brutal du script et donc une réponse vide 

pour la second l'erreur est bien gérée et elle apparaît dans lodex

mais tout cela n'explique pas la cause des erreurs

**Comment by cuxac** [comment]
Le service a été mis à jour pour corriger le pb de retour d'erreur non géré.
Une route a été ajoutée : on  peut soit traiter un pdf via son url, soit déposer un pdf via IA_Factory
