### ISSUE TITLE
Le précalcul noiseDetect ne fonctionne pas dans Lodex

### ISSUE THREAD

**Issue by MathildeHuguin** [Inist-CNRS/web-services#144]
Après plusieurs tentatives, le web-service _noiseDetect_ [https://text-clustering.services.istex.fr/v1/noise](https://text-clustering.services.istex.fr/v1/noise) ne fonctionne pas dans Lodex (essai effectué sur les résumés Istex d'un corpus de 2 000 documents).
Concrètement, il est affiché comme _terminé_ , les précalculs sont vides et ce message d'erreur apparaît : 

![image](https://github.com/user-attachments/assets/e5d482ab-b745-4731-a06e-63cac96c04be)

Logs : 

![image](https://github.com/user-attachments/assets/3b22fe5a-aa76-4a71-bc1e-f53ab779a224)

**Comment by touv** [comment]
Le web service retourne à priori une liste de "chaine de caractère" exemple : 

```
[
  "#A",
  "#B",
  "#C",
  "#D",
  "#E"
]
```

Cette structure est incompatible avec Lodex, il est obligatoire d'avoir des objets et de respecter un minima une structure {id value}

exemple : 

```  
[
  {  id: 1, value: "#A" },
  {  id: 2, value: "#B" },
  {  id: 3, value: "#C" },
  {  id: 4, value: "#D" },
  {  id: 5, value:  "#E" }
]
```

**Comment by leogail** [comment]
J'ai ajouté une route à utiliser dans Lodex dans la version [ws-text-clustering@1.2.0](https://github.com/Inist-CNRS/web-services/pull/85/commits/728115608993ebf7365d00035b25977931c9ca12)
