### ISSUE TITLE
Le ws bso (bilbiotools) renvoie énormément de "n/a" et d'erreurs

### ISSUE THREAD

**Issue by AnaelKremer** [Inist-CNRS/web-services#176]
Testé sur un corpus de 20 000 documents j'obtenais plus 6000 erreurs et 10 000 réponses "n/a" alors que si je vérifie manuellement les doi sur le dataset du BSO sur lequel fonctionne l'api je trouve bien les doi en question avec des données correspondantes.

Ce DOI par exemple a renvoyé "n/a" dans Lodex alors que le swagger indique une erreur...

![image](https://github.com/user-attachments/assets/4638b744-7437-4201-bbc5-b174367d279e)

**Comment by parmentf** [comment]
Le `Too Many Requests` indique que le service a dépassé une limite auprès de l'API utilisée.
https://github.com/Inist-CNRS/web-services/blob/3ee6faab1c6a2d516adb212c8e09683138c5c7c4/services/biblio-tools/v2/bso/works/expand.ini#L74

Il faudrait trouver quelles sont ses limites avant de pouvoir remédier au problème.

**Comment by AnaelKremer** [comment]
![image](https://github.com/user-attachments/assets/fce1b501-a40e-4e6e-a878-eb8bba725046)

**Comment by parmentf** [comment]
On sait quel est le problème (limitation à 10000 requêtes par jour), mais je ne vois pas comment s'y conformer (typiquement, on a des dizaines de milliers de documents à traiter, on ne va pas répartir les requêtes sur plusieurs journées).
