### ISSUE TITLE
[data-thesesul] Le test plante quand on est dans un replica à 2 pods

### ISSUE THREAD

**Issue by parmentf** [Inist-CNRS/web-services#191]
Le test de `data-thesesul` passe bien quand on n'a qu'un seul serveur ezs.

Mais quand on répartit les requêtes sur plusieurs serveurs (sur des machines différentes), le `retrieve-test` plante: il a une instruction `exec` sans inclusion du plugin `spawn`!

Symptôme (sur un _replica_ à 2 _pods_):

```bash
$ npx hurl --test --insecure --variable host="https://data-thesesul.vkdwebservices-api.intra.inist.fr" services/data-thesesul/tests.hurl
services/data-thesesul/tests.hurl: Running [1/1]
error: Assert status code
  --> services/data-thesesul/tests.hurl:32:6
   |
   | POST {{host}}/v1/retrieve-tests
   | ...
32 | HTTP 200
   |      ^^^ actual value is <400>
   |

services/data-thesesul/tests.hurl: Failure (2 request(s) in 11130 ms)
--------------------------------------------------------------------------------
Executed files:  1
Succeeded files: 0 (0.0%)
Failed files:    1 (100.0%)
Duration:        11133 ms
```

Je n'ai pas le log sous la main, mais c'est lui qui m'a indiqué que ezs ne pouvait pas exécuter `exec` (parce que `spawn` n'était pas chargé).

Ce n'est peut-être pas à corriger, puisque ce test est destiné à être réécrit avec un `sha256sum` qui compare l'empreinte du fichier renvoyé avec l'empreinte du fichier attendu.

**Comment by leogail** [comment]
Les tests ont été modifiés dans la PR [204](https://github.com/Inist-CNRS/web-services/pull/204)
